### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by mczernin** [drewwilson/atvImg#12]
First of all: This script is great!!! I love how easy & light it is!!!

In Chrome & IE the effect is great (i haven`t tested Firefox yet). But in Safari it seems that only the shining effect but not the 3D Animation works... Anything i do wrong?

Cheers,
Max

**Comment by drewwilson** [comment]
hey! thanks :) 
the code works in safari. if you have a specific bug, send a link to it or show me with a video or something.
thanks!
Drew
