### ISSUE TITLE
Don't work with Firefox

### ISSUE THREAD

**Issue by JSteunou** [drewwilson/atvImg#3]
Nice effect with Chrome, but totally broken under firefox when visiting your demo

**Comment by drewwilson** [comment]
Which version of Firefox? Works perfect for me on desktop. 
Thanks!

**Comment by JSteunou** [comment]
41.0.2

Sometimes it works, but very slow and laggy, whereas on Chrome it's perfect.

**Comment by JSteunou** [comment]
Reading your code very quickly, you might add some `requestAnimationFrame` call ;)

**Comment by mistic100** [comment]
I confirm it's really laggy, there is like a 500ms delay between the mouse move and the animation.

**Comment by davidgorges** [comment]
It is broken in Firefox 40.0.3 and FF 42.0.0 on OSX: It seems to be an issue with the scrollTop / event position. As you can see [this example](http://leap.li/atvmg-3): The further you scroll down, the higher the rotation angle on the image.

**Comment by Oblik-Design** [comment]
Really broken with firefox, if you've got multiple instances on a single page, the perspective get's all wrong hte further down the page. last firefox version 42. All the rest is pretty neat, but no firefox support makes it a bit useless, it's a shame, I like yours more then parallax.js ! 
![atv](https://cloud.githubusercontent.com/assets/9968597/11487887/6a686b1c-9790-11e5-8ed2-7767956659f9.png)

**Comment by alexandru-paduraru** [comment]
@davidgorges any ideas on how to fix the scrollTop Event? I'm having the same issue on firefox Mozilla

**Comment by Oblik-Design** [comment]
nop, it's a problem with rotateX() when lower on the page, that's all I know

**Comment by alexandru-paduraru** [comment]
@Oblik-Design so how can we fix this? I see that the xRotate = (dy - offsetY)*(0.1 \* wMultiple); is getting very high on firefox, but cannot figure it out how to fix it.

**Comment by Oblik-Design** [comment]
I really wish I knew how.

**Comment by Oblik-Design** [comment]
firefox is usually really good with js..

**Comment by alexandru-paduraru** [comment]
I've checked the javascript and it looks like on processMovement function line: 155 the "bdst = bd.topScroll" variable is always 0 on firefox so I switched it to bdst = $(window).scrollTop() and it is fixing the issue for the moment. Please check it and let me know if that was working on firefox.

**Comment by Oblik-Design** [comment]
nicely done, still it's a bit shaky, not smooth I mean, in my case. but finally usable !!

**Comment by alexandru-paduraru** [comment]
I was looking also for a solution for the smoothness trying to add a debounce function, so the processMovement will not be triggered 1000 times/second it will be triggered 60 times (so gain the 60FPS effect) but nothing special there. I'll start checking the timing for the CSS maybe that is causing the problems.

**Comment by Oblik-Design** [comment]
well , in my script i've removed, in a test, the shine div and shadow div that are generated on mousemove, it's now perfect fast. but it is working my fans... I'm not a good js programmer..

**Comment by davidgorges** [comment]
@alexandru-paduraru requestAnimationFrame ftw.

**Comment by drewwilson** [comment]
I've just added a fix for the perspective issue in Firefox. Grab the latest for that.
I haven't noticed any slowness on my machine.. looks to be a bit slower than chrome and safari, but Firefox always is for most things.

**Comment by Oblik-Design** [comment]
works, tks !
