### ISSUE TITLE
cannot get it running

### ISSUE THREAD

**Issue by MaxPower87** [drewwilson/atvImg#7]
First of all i apologize for my stupid question. :smile: 
im not familiar with javascript but i want to test your cool plugin.

i created the following html page, but i dont get the plugin running at all.

```
<html>
<body>
<div class="atvImg">
   <img src="/images/Mario-Mushroom.png">
   <div class="atvImg-layer" data-img="/images/Mario-Mushroom.png"></div>
</div>
<script type="javascript" src="atvImg.js"></script>
<script>atvImg();</script>
</body>
</html>
```

The paths are correct but i only see the flattened image :disappointed: 

THX so much

**Comment by far0s** [comment]
You need to have multiple "atvImg-layer" divs to have the effect.

In your case you set the flattened image and your layer to be the same image, you need to separate the differents layers you want and export them in separate .pngs ;-)

For example : one .png with mario, one with the background, one with the level elements, etc...
