### ISSUE TITLE
no image displaying

### ISSUE THREAD

**Issue by jothachil** [drewwilson/atvImg#9]
<div class="atvImg">
         <img src="images/flattened-icon.jpg">

```
     <div class="atvImg-layer" data-img="images/back.png"></div>
     <div class="atvImg-layer" data-img="images/front.png"></div>
  </div>
```

used same images as give in demo site

**Comment by drewwilson** [comment]
hey!
the code you've pasted is incomplete. also, if you haven't downloaded those images they won't display for you because they won't exist on your machine unless you download them.
thanks!
Drew
